### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by Define-Skellyton** [slundi/RatioUp#7]
Unable to initate with docker, is it possible to get a release so it can be pulled?

**Comment by slundi** [comment]
Hi

I'm sorry, I don't have time those days so it is not progressing fast.
I was fixing the spawn of tracker query every X minutes... but it is not simple.

**Comment by DCollart** [comment]
@Define-Skellyton I had the same issue because the "latest" tag (which is the default one) is missing in the registry  so this does not work: 

`docker pull slundi/ratioup`

You can provide an existing tag and and it should solve this specific problem : 

`docker pull slundi/ratioup:latest_x86_64`

You can find the existing tags here: https://hub.docker.com/r/slundi/ratioup/tags

**Comment by labdiynez** [comment]
@slundi 

exec /app/RatioUp: exec format error

**Comment by Jack74r** [comment]
> @Define-Skellyton I had the same issue because the "latest" tag (which is the default one) is missing in the registry so this does not work:
> 
> `docker pull slundi/ratioup`
> 
> You can provide an existing tag and and it should solve this specific problem :
> 
> `docker pull slundi/ratioup:latest_x86_64`
> 
> You can find the existing tags here: https://hub.docker.com/r/slundi/ratioup/tags

Hi, i try x86_64 but it's doesn't work for me

i try to use the sha for latest amd64 image: slundi/ratioup:latest@sha256:05041ed31809c1a0d4a7f0e6b9dcbe6a3c073430083bed88bd8e7a72e1e427f0 but wont start

**Comment by slundi** [comment]
Hi
I did not work on it for a while. The multi-arch build with may have failed.

So I'll try to do a amd64 one only as soon as I can

**Comment by slundi** [comment]
Finally, I'll drop docker support. With cargo, it is easy to have the binary.

I may make an installer later.
